name: ztdloneday
channels:
- defaults
dependencies:
- python=3.7.*
- numpy==1.16.*
- cython==0.29.*
- h5py==2.9.*
- jupyter==1.0.*
- matplotlib==3.0.*
- pandas==0.24.*
- pip==19.0.*
- pytest==4.3.*
- scipy==1.2.*
- seaborn==0.9.*
- pip:
  - tensorflow==2.0.0-alpha0
